### ISSUE TITLE
colx-1.0.3-x86_64-linux-gnu.tar.gz does not contains colx-qt

### ISSUE THREAD

**Issue by kroupouk666** [ColossusCoinXT/ColossusCoinXT#10]
Team,

Is there any reasons whycolx-1.0.3-x86_64-linux-gnu.tar.gz does not contains colx-qt?

Thanks!

**Comment by pavik** [comment]
Files has just updated, thank you for reporting this issue. Direct link https://github.com/ColossusCoinXT/ColossusCoinXT/releases/download/v1.0.3/colx-1.0.3-x86_64-linux-gnu.tar.gz
