### ISSUE TITLE
AddressIndex

### ISSUE THREAD

**Issue by eabz** [ColossusCoinXT/ColossusCoinXT#11]
I see the COLX is a PIVX fork.
We are working on integrating it on PolisPay but we are using a block explorer to get that balance information.
Do you have plans to implement addressindex to get the utxo?

**Comment by pavik** [comment]
Yes, we have such plans. Could you give us the list of missing API that will be helpful for integration?

**Comment by eabz** [comment]
Hello @pavik 
Actually I implemented another solution, we are doing an internal txindex and parsing them.
But it will be very usefull for COLX (and also for all PIVX forks) to integrate it. 
There is one example on litecoin that integrates it, I actually try it but it was consuming a lot of time and don't know the COLX code. 
https://github.com/litecoin-project/litecore-litecoin
Here you can see how they integrate the RPC calls.

**Comment by pavik** [comment]
Thank you.

**Comment by eabz** [comment]
@pavik 
I am closing this. We are looking another approach.
